### ISSUE TITLE
Need to set new version for package in npm.

### ISSUE THREAD

**Issue by chebanenko** [BuBuaBu/gitlab-ci-lint#30]
Hi, @BuBuaBu.
First of all, thanks for accepting MR.
Could you bump the version of the "gitlab-ci-lint" package in npm?

**Comment by ThePlenkov** [comment]
haha- just faced same issue. Was trying to figure our why token doesn't work. Will use now temporarily git dependency. Thanks for adding this feature

**Comment by chebanenko** [comment]
Resolved in https://github.com/BuBuaBu/gitlab-ci-lint/pull/31
